spring:
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/orclcntr
    username: shop
    password: alireza_poyarayaneh
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle10gDialect


